### ISSUE TITLE
Link player names if-and-only-if the player has a page on Wikipedia

### ISSUE THREAD

**Issue by hamilr2** [vreelb/CollegeHockeyWikiTables#7]
Some more famous players (Jack Eichel, for example) have pages that should be linked from their roster.

Some players could have a name shared with someone else that has a page, or perhaps their name links to a disambiguation page, which could make things tricky.

**Comment by vreelb** [comment]
Basically #5, but yes. I wonder if the wikipedia API has something for that.

**Comment by vreelb** [comment]
Closing with extreme prejudice.
